background.js, content_script_all_frames.js, content_script_parent.js, inject.js, manifest.json, options.html, options.js, popup.html, popup.js
Chrome has a page just for changing extensions' shortcuts and doesn't
support Firefox's/standard WebExtensions's way of doing it.
=> firefox: add way to change shortcuts

inject.js
Fixing my Issue #76 - Broken links in glide_list when defined as Choice
Root cause is that if "Reference" field in Dictionary is empty, g_form.getGlideUIElement(field).reference returns "null" as a string. Therefore the condition !table did not work.
=> Fixed links in glide_list if field reference table is not set

inject.js
=> createHyperLinkForGlideLists: only add links for SysID-like values

content_script_all_frames.js
=> content_script_all_frames: fix regression from eb18a05f0

inject.js
=> technical-names: add links on icon instead of field name

background.js
The context menu action "Copy Selected Cell Values from List" does nothing on click.
=> Fix the context menu action

inject.js
The issue is described here: #128 
I did not delete global variables qry and qryDisp since they are used in the generateATFValues function. I was not able to find where this function is called from.
=> Fix: processing issue in the clickToList function

inject.js
The feature request is described here: #150.
=> Show hidden variables

inject.js
The issue is described here: #153.
=> Fix: sort of grouped record breaks the URL

inject.js
The issue is described here: #160.
=> Fix: processing issue in the snuCaptureFormClick function

inject.js
The feature allows updating related list queries using double-click.
=> Feature: breadcrumbs double-click in related lists

inject.js
The feature request is described here: #163.
=> Filter out for the form view

inject.js
The issue is described here: #167.
=> Fix: issue in the snuDoubleClickToShowFieldOrReload function

content_script_all_frames.js
The issue is described here: #171.
=> Fix: missing else

inject.js
The issue is described here: #173.
=> Date fix for the "snuCaptureFormClick" function

inject.js
Implementing the #175 + jQuery to vanilla js.
=> Cat item variables in the snuCaptureFormClick function

inject.js
=> Fix: users can remove items from read-only list

inject.js
=> Fix: null exception fix in the snuDoubleClickToShowFieldOrReload function

inject.js
=> Fix: JS error in the background script

inject.js
=> Fix: unexpected behavior in the snuCaptureFormClick function

codeeditor.html, css/codeeditor.css, js/monaco/codeeditor.js
- Adds additional selectors to style the HTML.
- Updates css to fix the overflow issue. 
- Adds arrow icon to the go to tab link in the header.
- Adds a class allowing the option to display the header at the footer of of the code editor for user-preferences. Note: I don't know how to implement this via JS, I've never worked with a chrome ext. before.
=> * Changed the codeeditor.html to fix overflow issue.

inject.js
=> Fix: switching application in Polaris

content_script_parent.js
=> Fix: wrong property name

js/monaco/monaco.js
=> Autofocus in the background script (monaco editor)

inject.js
=> Fix: wrong link on the order form after using /tn

inject.js
=> Edit condition fields in the Monaco editor

background.js
=> Fix broken context menu action

inject.js
This will make it easier when being on a specific record to go to the list.
=> Add view list as Slash switches

popup.js
=> Removing FF options leftovers

popup.html
=> Removing cosmetic FF options leftovers

inject.js
=> /app slashcommand fix

js/monaco/monaco.js
Hey I was working on something in background script and thought it would be nice to have a link to cancel the transaction as it ran.
=> Add cancel my transaction to background scripts running counter

popup.js
=> Fix links with no text

inject.js
=> Fix unsupported duration fields when building query on the form view

popup.js
=> Fix null table in GlideRecord tab

popup.js
=> Fix unescaped double quote

inject.js
=> Fix sysparm_view value in the crn command

inject.js
=> Fix js commands that contain the sysparm_query substring
